# Generated by Django 3.1.1 on 2020-09-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='Blank', max_length=256),
        ),
    ]
